using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.SessionState;
using BTL_LapTrinhWeb.Models;

namespace BTL_LapTrinhWeb
{
    public class Global : System.Web.HttpApplication
    {

        protected void Application_Start(object sender, EventArgs e)
        {
            List<Products> allProducts = new List<Products>
            {
                new Products { ProductID = 1, Name = "Jordan 1 Retro Low OG SP Fragment x Travis Scott", Price = 1227M, ImageUrl = "~/Assets/images/Men/shoes_man_1.png", Category = "Sneakers", ProductUrl = "#", Gender="Men", Sale = 30, ImageBack = "~/Assets/images/Men/anh1_back.png", ImageLeft = "~/Assets/images/Men/anh1_left.jpg", ImageTop = "~/Assets/images/Men/anh1_top.png", ImageUnder = "~/Assets/images/Men/anh1_under.png" , Description="Channeling the sample pair teased by Hiroshi back in 2021, the 2025 Fragment x Travis Scott x Air Jordan 1 Low OG retail version will see a white-based leather upper, with sail-tinted midsoles and a sea of Military Blue trimming, including the famous reverse Swoosh."},
                new Products { ProductID = 2, Name = "Jordan 1 Retro Low OG SP Travis Scott Reverse Mocha", Price = 1139M, ImageUrl = "~/Assets/images/Men/shoes_man_2.png", Category = "Sneakers", ProductUrl = "#", Gender="Men", Sale = 0, ImageBack = "~/Assets/images/Men/anh2_back.png", ImageLeft = "~/Assets/images/Men/anh2_left.png", ImageTop = "~/Assets/images/Men/anh2_top.png", ImageUnder = "~/Assets/images/Men/anh2_under.png" , Description="Nodding to the Air Jordan 1 High Travis Scott Mocha, the Air Jordan 1 Low Travis Scott Reverse Mocha offers a similar Mocha and off-white palette but in a reverse-style color blocking. Its upper is constructed with a Mocha Durabuck base, white leather overlays, and signature reverse Swooshes." },
                new Products { ProductID = 3, Name = "Jordan 1 Retro Low OG SP Travis Scott Black Phantom", Price = 580M, ImageUrl = "~/Assets/images/Men/shoes_man_3.png", Category = "Sneakers", ProductUrl = "#", Gender="Men",Sale = 0, ImageBack = "~/Assets/images/Men/anh3_back.jpg", ImageLeft = "~/Assets/images/Men/anh3_left.png", ImageTop = "~/Assets/images/Men/anh3_top.png", ImageUnder = "~/Assets/images/Men/anh3_under.png" , Description="The all black nubuck sneakers feature a Nike Air logo on the tongue and an Air Jordan Wings logo on the right heel tab. Red, Black, and White/Black laces are included and an embroidered Bee is located on the heel tab of the left sneaker inspired by Travis’ daughter, Stormi." },
                new Products { ProductID = 4, Name = "Adidas Samba OG Cloud White Core Black", Price = 44M, ImageUrl = "~/Assets/images/Men/shoes_man_4.png", Category = "Lifestyles/Casual", ProductUrl = "#", Gender="Men", Sale = 30, ImageBack = "~/Assets/images/Men/anh4_back.png", ImageLeft = "~/Assets/images/Men/anh4_left.png", ImageTop = "~/Assets/images/Men/anh4_top.png", ImageUnder = "~/Assets/images/Men/anh4_under.png" , Description="The Adidas Samba OG Cloud White Core Black is a classic and versatile sneaker, known for its timeless style. It features a clean Cloud White full-grain leather upper, contrasted with iconic Core Black serrated 3-Stripes and a signature suede T-toe. Rooted in indoor soccer heritage, this low-profile shoe maintains its original design with a comfortable low-cut silhouette and a distinct gum rubber outsole, making it an enduring streetwear icon." },
                new Products { ProductID = 5, Name = "Adidas Samba OG Black Green Leopard", Price = 50M, ImageUrl = "~/Assets/images/Men/shoes_man_5.png", Category = "Lifestyles/Casual", ProductUrl = "#", Gender="Men", Sale = 0, ImageBack = "~/Assets/images/Men/anh5_back.png", ImageLeft = "~/Assets/images/Men/anh5_left.png", ImageTop = "~/Assets/images/Men/anh5_top.png", ImageUnder = "~/Assets/images/Men/anh5_under.png" , Description="This is a bold, fashion-forward update to the classic Samba silhouette. This women's exclusive model features a striking all-over leopard print on a faux pony hair upper, contrasted with Core Black leather overlays. A pop of Collegiate Green lines the interior. It retains the signature low-cut shape and the classic gum rubber outsole, blending a wild, modern aesthetic with an enduring retro style." },
                new Products { ProductID = 6, Name = "Puma LaMelo Ball MB.04 Lo Alien Skin", Price = 51M, ImageUrl = "~/Assets/images/Men/shoes_man_6.png", Category = "Sports", ProductUrl = "#", Gender="Men",Sale = 40, ImageBack = "~/Assets/images/Men/anh6_back.png", ImageLeft = "~/Assets/images/Men/anh6_left.png", ImageTop = "~/Assets/images/Men/anh6_top.png", ImageUnder = "~/Assets/images/Men/anh6_under.png" , Description="The Puma LaMelo Ball MB.04 Lo \"Alien Skin\" is a low-cut basketball shoe and the debut colorway of the MB.04 Lo silhouette, inspired by LaMelo Ball's \"Not From This Earth\" style of play.\r\n\r\nThis sneaker features a supportive double-layered mesh upper entirely wrapped in a unique, all-over extraterrestrial (alien) texture in a vibrant colorway (Ultra Blue-Luminous Pink-Green Glare). It includes the signature Melo wing logo wrapping around the heel. Built for on-court performance, it utilizes PUMA's responsive NITROFOAM™ cushioning and features an outsole with an alien-themed traction pattern and LaMelo's catchphrases, \"NOT FROM HERE\" and \"RARE.\"" },
                new Products { ProductID = 7, Name = "Puma LaMelo Ball MB.04 Lo Ice White", Price = 54M, ImageUrl = "~/Assets/images/Men/shoes_man_7.png", Category = "Sports", ProductUrl = "#", Gender="Men", Sale = 0, ImageBack = "~/Assets/images/Men/anh7_back.png", ImageLeft = "~/Assets/images/Men/anh7_left.png", ImageTop = "~/Assets/images/Men/anh7_top.png", ImageUnder = "~/Assets/images/Men/anh7_under.png" , Description="Puma LaMelo Ball MB.04 Lo \"Ice White\" The low-cut version of LaMelo Ball's fourth signature shoe, featuring PUMA's performance technology (like NITROFOAM™) in a sleek, predominantly white colorway. It retains the MB.04's design, inspired by Melo's \"Not From This Earth\" play style." },
                new Products { ProductID = 8, Name = "New Balance 9060 Gray Jet Black", Price = 102M, ImageUrl = "~/Assets/images/Men/shoes_man_8.png", Category = "Sports", ProductUrl = "#", Gender="Men", Sale = 0, ImageBack = "~/Assets/images/Men/anh8_back.png", ImageLeft = "~/Assets/images/Men/anh8_left.png", ImageTop = "~/Assets/images/Men/anh8_top.png", ImageUnder = "~/Assets/images/Men/anh8_under.png" , Description="New Balance 9060 \"Gray Jet Black\" A lifestyle sneaker that updates the classic 99X series with a futuristic, exaggerated Y2K-era aesthetic. It features a grey and black upper, wavy lines, and a chunky sculpted midsole with both ABZORB and SBS cushioning." },
                new Products { ProductID = 9, Name = "New Balance 9060 Arid Stone Mushroom", Price = 116M, ImageUrl = "~/Assets/images/Men/shoes_man_9.png", Category = "Sports", ProductUrl = "#", Gender="Men", Sale = 50, ImageBack = "~/Assets/images/Men/anh9_back.png", ImageLeft = "~/Assets/images/Men/anh9_left.png", ImageTop = "~/Assets/images/Men/anh9_top.png", ImageUnder = "~/Assets/images/Men/anh9_under.png" , Description="New Balance 9060 \"Arid Stone Mushroom\" This 9060 colorway presents a neutral, earth-toned look with an \"Arid Stone\" (tan/beige) and \"Mushroom\" palette. It is a modernized silhouette that delivers maximal comfort and a unique, chunky style inspired by New Balance's heritage." },
                new Products { ProductID = 10, Name = "Nike Air Force 1 Low '07 White", Price = 62M, ImageUrl = "~/Assets/images/Men/shoes_man_10.png", Category = "Sneakers", ProductUrl = "#", Gender="Men", Sale = 0, ImageBack = "~/Assets/images/Men/anh10_back.png", ImageLeft = "~/Assets/images/Men/anh10_left.png", ImageTop = "~/Assets/images/Men/anh10_top.png", ImageUnder = "~/Assets/images/Men/anh10_under.png" , Description="Nike Air Force 1 Low '07 White The timeless, legendary basketball original now a street icon. It features a clean, all-white leather upper with durably stitched overlays, a low-cut silhouette, and the classic Nike Air cushioning for all-day comfort." },
                new Products { ProductID = 11, Name = "Nike SB Dunk Low Futura Laboratories Bleached Aqua", Price = 152M, ImageUrl = "~/Assets/images/Men/shoes_man_11.png", Category = "Sneakers", ProductUrl = "#", Gender="Men", Sale = 0, ImageBack = "~/Assets/images/Men/anh11_back.png", ImageLeft = "~/Assets/images/Men/anh11_left.png", ImageTop = "~/Assets/images/Men/anh11_top.png", ImageUnder = "~/Assets/images/Men/anh11_under.png" , Description="Nike SB Dunk Low Futura Laboratories \"Bleached Aqua\" A highly anticipated collaboration with legendary artist Futura, this Nike SB Dunk Low features his signature abstract graffiti-style artwork on the upper, often combining white, black, and a vibrant \"Bleached Aqua\" blue." },
                new Products { ProductID = 12, Name = "Timberland 6\" Boot Black Nubuck Premium", Price = 119M, ImageUrl = "~/Assets/images/Men/shoes_man_17.png", Category = "Boots", ProductUrl = "#", Gender="Men", Sale = 0, ImageBack = "~/Assets/images/Men/anh12_back.png", ImageLeft = "~/Assets/images/Men/anh12_left.png", ImageTop = "~/Assets/images/Men/anh12_top.png", ImageUnder = "~/Assets/images/Men/anh12_under.png" , Description="Timberland 6\" Boot Black Nubuck Premium The iconic, rugged waterproof boot. This premium version is crafted from durable black nubuck leather, featuring sealed construction and PrimaLoft insulation, making it a staple for protection, durability, and classic style." },
                new Products { ProductID = 13, Name = "Adidas Yeezy 500 High Tactical Boot Utility Black", Price = 73M, ImageUrl = "~/Assets/images/Men/shoes_man_18.png", Category = "Boots", ProductUrl = "#", Gender="Men", Sale = 0, ImageBack = "~/Assets/images/Men/anh13_back.png", ImageLeft = "~/Assets/images/Men/anh13_left.png", ImageTop = "~/Assets/images/Men/anh13_top.png", ImageUnder = "~/Assets/images/Men/anh13_under.png" , Description="Adidas Yeezy 500 High Tactical Boot \"Utility Black\" A high-top, tactical-inspired boot that combines the design language of the Yeezy 500 with a more rugged, utilitarian build. It comes in an all-\"Utility Black\" colorway, offering durability, ankle support, and a sleek, modern aesthetic." },
                new Products { ProductID = 14, Name = "Jordan 1 Retro High OG Washed Pink", Price = 100M, ImageUrl = "~/Assets/images/Women/shoes_women1.png", Category = "Sneakers", ProductUrl = "#", Gender="Women", Sale = 0, ImageBack = "~/Assets/images/Women/anh1_back.png", ImageLeft = "~/Assets/images/Women/anh1_left.png", ImageTop = "~/Assets/images/Women/anh1_top.png", ImageUnder = "~/Assets/images/Women/anh1_under.png" , Description="Jordan 1 Retro High OG \"Washed Pink\" This Air Jordan 1 features a muted, vintage-inspired look with soft pink suede overlays on a white leather base. It provides the iconic high-top silhouette with a gentle, \"washed\" aesthetic, perfect for a subtle, stylish statement." },
                new Products { ProductID = 15, Name = "Jordan 11 Retro Low Legend Pink", Price = 94M, ImageUrl = "~/Assets/images/Women/shoes_women2.png", Category = "Sneakers", ProductUrl = "#", Gender="Women", Sale = 0, ImageBack = "~/Assets/images/Women/anh2_back.png", ImageLeft = "~/Assets/images/Women/anh2_left.png", ImageTop = "~/Assets/images/Women/anh2_top.png", ImageUnder = "~/Assets/images/Women/anh2_under.png" , Description="Jordan 11 Retro Low \"Legend Pink\" A women's sneaker featuring the classic Air Jordan 11 Low silhouette. It utilizes a clean white ballistic mesh upper with a distinct, shining Legend Pink patent leather mudguard, offering lightweight cushioning and an elegant, vibrant look." },
                new Products { ProductID = 16, Name = "Jordan 4 Retro Off-White Sail", Price = 1362M, ImageUrl = "~/Assets/images/Women/shoes_women3.png", Category = "Sneakers", ProductUrl = "#", Gender="Women", Sale = 30, ImageBack = "~/Assets/images/Women/anh3_back.png", ImageLeft = "~/Assets/images/Women/anh3_left.png", ImageTop = "~/Assets/images/Women/anh3_top.png", ImageUnder = "~/Assets/images/Women/anh3_under.png" , Description="Jordan 4 Retro Off-White \"Sail\" A highly coveted collaboration with Virgil Abloh’s Off-White, this Jordan 4 is defined by its deconstructed elements, signature text graphics, and a premium \"Sail\" (cream/off-white) monochromatic colorway. It is a masterpiece of modern luxury streetwear." },
                new Products { ProductID = 17, Name = "ASICS Gel-1130 Neon Pack Pink", Price = 85M, ImageUrl = "~/Assets/images/Women/shoes_women4.png", Category = "Sports", ProductUrl = "#", Gender="Women", Sale = 0, ImageBack = "~/Assets/images/Women/anh4_back.png", ImageLeft = "~/Assets/images/Women/anh4_left.png", ImageTop = "~/Assets/images/Women/anh4_top.png", ImageUnder = "~/Assets/images/Women/anh4_under.png" , Description="ASICS Gel-1130 \"Neon Pack Pink\" Part of the \"Neon Pack,\" this iteration of the ASICS Gel-1130 pays tribute to late-2000s runners. It features a bright Fuchsia Pink mesh design with synthetic overlays and the signature GEL™ cushioning for comfort and a bold, retro-tech look." },
                new Products { ProductID = 18, Name = "ASICS Novablast 5 Tokyo Vapor Edo Purple", Price = 107M, ImageUrl = "~/Assets/images/Women/shoes_women5.png", Category = "Sports", ProductUrl = "#", Gender="Women", Sale = 50, ImageBack = "~/Assets/images/Women/anh5_back.png", ImageLeft = "~/Assets/images/Women/anh5_left.png", ImageTop = "~/Assets/images/Women/anh5_top.png", ImageUnder = "~/Assets/images/Women/anh5_under.png" , Description="ASICS Novablast 5 Tokyo \"Vapor Edo Purple\" A high-performance running shoe from ASICS' Tokyo collection. It features a lightweight design with an energetic FF BLAST™ MAX cushioning and a trampoline-inspired outsole for a highly responsive ride, colored in a striking \"Vapor Edo Purple.\"" },
                new Products { ProductID = 19, Name = "ASICS Gel-1130 Baby Lavender Pure Silver", Price = 105M, ImageUrl = "~/Assets/images/Women/shoes_women6.png", Category = "Sports", ProductUrl = "#", Gender="Women", Sale = 0, ImageBack = "~/Assets/images/Women/anh6_back.png", ImageLeft = "~/Assets/images/Women/anh6_left.png", ImageTop = "~/Assets/images/Women/anh6_top.png", ImageUnder = "~/Assets/images/Women/anh6_under.png" , Description="ASICS Gel-1130 \"Baby Lavender Pure Silver\" This Gel-1130 offers a lighter, pastel color scheme with a Baby Lavender mesh upper accented by gleaming Pure Silver overlays. It's a comfortable, heritage-inspired runner that delivers both a retro vibe and modern cushioning." },
                new Products { ProductID = 20, Name = "Adidas Samba Ruffle Stripes Pack Wonder Mauve", Price = 71M, ImageUrl = "~/Assets/images/Women/shoes_women7.png", Category = "Lifestyles/Casual", ProductUrl = "#", Gender="Women", Sale = 0, ImageBack = "~/Assets/images/Women/anh7_back.png", ImageLeft = "~/Assets/images/Women/anh7_left.png", ImageTop = "~/Assets/images/Women/anh7_top.png", ImageUnder = "~/Assets/images/Women/anh7_under.png" , Description="Adidas Samba Ruffle Stripes Pack \"Wonder Mauve\" A feminine and unique twist on the classic Samba, this model features soft Wonder Mauve (pinkish-purple) tones. The iconic 3-Stripes are replaced with delicate, ruffled fabric, giving the sneaker a soft, fashionable, and eye-catching flair." },
                new Products { ProductID = 21, Name = "Adidas Handball Spezial Semi Lucid Fuchsia Lucid Pink Gold Metallic", Price = 115M, ImageUrl = "~/Assets/images/Women/shoes_women8.png", Category = "Lifestyles/Casual", ProductUrl = "#", Gender="Women", Sale = 0, ImageBack = "~/Assets/images/Women/anh8_back.png", ImageLeft = "~/Assets/images/Women/anh8_left.png", ImageTop = "~/Assets/images/Women/anh8_top.png", ImageUnder = "~/Assets/images/Women/anh8_under.png" , Description="Adidas Handball Spezial \"Semi Lucid Fuchsia Lucid Pink Gold Metallic\" An indoor sports classic from the archives, this Spezial features a soft suede upper in a vibrant mix of Semi Lucid Fuchsia and Lucid Pink. It is finished with a classic gum rubber outsole and luxurious Gold Metallic accents for a standout retro look." },
                new Products { ProductID = 22, Name = "Nike A'ja Wilson A'One Pink A'ura", Price = 97M, ImageUrl = "~/Assets/images/Women/shoes_women9.png", Category = "Sports", ProductUrl = "#", Gender="Women", Sale = 30, ImageBack = "~/Assets/images/Women/anh9_back.png", ImageLeft = "~/Assets/images/Women/anh9_left.png", ImageTop = "~/Assets/images/Women/anh9_top.png", ImageUnder = "~/Assets/images/Women/anh9_under.png" , Description="Nike A'ja Wilson A'One \"Pink A'ura\" A performance basketball shoe, likely A'ja Wilson's signature line. The \"Pink A'ura\" colorway uses vibrant pink hues to reflect her bold personality and presence on the court, featuring a comfortable foam midsole for high energy and support." },
                new Products { ProductID = 23, Name = "Yeezy Military Boot Season 3 Onyx", Price = 700M, ImageUrl = "~/Assets/images/Women/shoes_women10.png", Category = "Boots", ProductUrl = "#", Gender="Women", Sale = 0, ImageBack = "~/Assets/images/Women/anh10_back.png", ImageLeft = "~/Assets/images/Women/anh10_left.png", ImageTop = "~/Assets/images/Women/anh10_top.png", ImageUnder = "~/Assets/images/Women/anh10_under.png" , Description="Yeezy Military Boot Season 3 \"Onyx\" A high-top boot from the Yeezy Season 3 line. It has a rugged, military-inspired aesthetic, featuring a durable build, heavy-duty sole, and a dark \"Onyx\" color scheme, positioned at the intersection of high fashion and utilitarian design." },
                new Products { ProductID = 24, Name = "Adidas Yeezy Desert Boot House Blue", Price = 422M, ImageUrl = "~/Assets/images/Women/shoes_women11.png", Category = "Boots", ProductUrl = "#", Gender="Women",Sale = 40, ImageBack = "~/Assets/images/Women/anh11_back.png", ImageLeft = "~/Assets/images/Women/anh11_left.png", ImageTop = "~/Assets/images/Women/anh11_top.png", ImageUnder = "~/Assets/images/Women/anh11_under.png" , Description="Adidas Yeezy Desert Boot \"House Blue\" A chunky, utilitarian boot inspired by military and desert footwear. It features a suede and mesh upper over a thick rubber sole, with a distinct color palette that includes shades of blue and earth tones (sometimes referred to as Taupe Blue)." },
                new Products { ProductID = 25, Name = "Puma Speedcat Ballet Whisp of Pink", Price = 48M, ImageUrl = "~/Assets/images/Women/shoes_women12.png", Category = "Lifestyles/Casual", ProductUrl = "#", Gender="Women", Sale = 0, ImageBack = "~/Assets/images/Women/anh12_back.png", ImageLeft = "~/Assets/images/Women/anh12_left.png", ImageTop = "~/Assets/images/Women/anh12_top.png", ImageUnder = "~/Assets/images/Women/anh12_under.png" , Description="Puma Speedcat Ballet \"Whisp of Pink\" A fashionable, low-profile lifestyle shoe inspired by motorsport, specifically F1 racing shoes. This model adapts the Speedcat silhouette with feminine ballet-flat styling, featuring a soft \"Whisp of Pink\" suede upper." },
                new Products { ProductID = 26, Name = "Puma Speedcat Ballet Silver", Price = 44M, ImageUrl = "~/Assets/images/Women/shoes_women13.png", Category = "Lifestyles/Casual", ProductUrl = "#", Gender="Women", Sale = 0, ImageBack = "~/Assets/images/Women/anh13_back.png", ImageLeft = "~/Assets/images/Women/anh13_left.png", ImageTop = "~/Assets/images/Women/anh13_top.png", ImageUnder = "~/Assets/images/Women/anh13_under.png" , Description="Puma Speedcat Ballet \"Silver\" Similar to the \"Whisp of Pink,\" this model is a fusion of motorsport and ballet aesthetics. It features a metallic or silver-toned upper, offering a sleek, glossy, and eye-catching look in a comfortable, driving-shoe-inspired design." },
                new Products { ProductID = 27, Name = "Nike Kid's Flex Runner 4 Slip on Running Shoe Toddler", Price = 40M, ImageUrl = "~/Assets/images/Kids/shoes_kid1.png", Category = "Sports", ProductUrl = "#", Gender="Kids", Sale = 0, ImageBack = "~/Assets/images/Kids/anh1_back.png", ImageLeft = "~/Assets/images/Kids/anh1_left.png", ImageTop = "~/Assets/images/Kids/anh1_top.png", ImageUnder = "~/Assets/images/Kids/anh1_under.png", Description="Nike Kid's Flex Runner 4 Slip on Running Shoe (Toddler) A highly flexible, slip-on shoe for young children. It features a bootie-like design with elastic straps for an easy on/off fit, with flex grooves in the sole to promote natural foot movement for active toddlers." },
                new Products { ProductID = 28, Name = "Nike Kids' Court Borough Recraft Low Top Sneaker Little Kid", Price = 69M, ImageUrl = "~/Assets/images/Kids/shoes_kid2.png", Category = "Sneakers", ProductUrl = "#", Gender="Kids", Sale = 0, ImageBack = "~/Assets/images/Kids/anh2_back.png", ImageLeft = "~/Assets/images/Kids/anh2_left.png", ImageTop = "~/Assets/images/Kids/anh2_top.png", ImageUnder = "~/Assets/images/Kids/anh2_under.png", Description="Nike Kids' Court Borough Recraft Low Top Sneaker (Little Kid) A low-top sneaker for kids, inspired by classic retro basketball designs. It features a durable, structured upper and a simple, sporty aesthetic, built with comfort and a familiar court-style look for everyday wear." },
                new Products { ProductID = 29, Name = "Nike Kids' Air Max 270 Sneaker Big Kid", Price = 132M, ImageUrl = "~/Assets/images/Kids/shoes_kid3.png", Category = "Sports", ProductUrl = "#", Gender="Kids", Sale = 30, ImageBack = "~/Assets/images/Kids/anh3_back.png", ImageLeft = "~/Assets/images/Kids/anh3_left.png", ImageTop = "~/Assets/images/Kids/anh3_top.png", ImageUnder = "~/Assets/images/Kids/anh3_under.png", Description="Nike Kids' Air Max 270 Sneaker (Big Kid) A lifestyle sneaker for older kids, featuring Nike's tallest heel Air unit for maximum cushioning. It offers a futuristic look with a comfortable, sock-like fit and bold color accents around the large, visible Air bubble." },
                new Products { ProductID = 30, Name = "New Balance Kids' 237 Slip On Retro Sneaker Toddler", Price = 55M, ImageUrl = "~/Assets/images/Kids/shoes_kid4.png", Category = "Sports", ProductUrl = "#", Gender="Kids", Sale = 0, ImageBack = "~/Assets/images/Kids/anh4_back.png", ImageLeft = "~/Assets/images/Kids/anh4_left.png", ImageTop = "~/Assets/images/Kids/anh4_top.png", ImageUnder = "~/Assets/images/Kids/anh4_under.png", Description="New Balance Kids' 237 Slip On Retro Sneaker (Toddler) This toddler version of the New Balance 237 adapts the retro-running style into a convenient slip-on. It features a large \"N\" logo, a mix of suede/synthetic materials, and a comfortable design, bringing a heritage look to little feet." },
                new Products { ProductID = 31, Name = "Converse Kids' Chuck Taylor All Star 1V High Top Sneaker Little Kid", Price = 40M, ImageUrl = "~/Assets/images/Kids/shoes_kid5.png", Category = "Lifestyles/Casual", ProductUrl = "#", Gender="Kids", Sale = 0, ImageBack = "~/Assets/images/Kids/anh5_back.png", ImageLeft = "~/Assets/images/Kids/anh5_left.png", ImageTop = "~/Assets/images/Kids/anh5_top.png", ImageUnder = "~/Assets/images/Kids/anh5_under.png", Description="Converse Kids' Chuck Taylor All Star 1V High Top Sneaker (Little Kid) The iconic Chuck Taylor high-top canvas sneaker, specifically designed for kids. The \"1V\" model replaces laces with a single adjustable hook-and-loop strap and elastic laces for easy on/off and a secure fit." },
                new Products { ProductID = 32, Name = "Bearpaw Kids' Elle Youth Short Water Resistant Boot Little/Big Kid", Price = 124M, ImageUrl = "~/Assets/images/Kids/shoes_kid6.png", Category = "Boots", ProductUrl = "#", Gender="Kids", Sale = 30, ImageBack = "~/Assets/images/Kids/anh6_back.png", ImageLeft = "~/Assets/images/Kids/anh6_left.png", ImageTop = "~/Assets/images/Kids/anh6_top.png", ImageUnder = "~/Assets/images/Kids/anh6_under.png", Description="Bearpaw Kids' Elle Youth Short Water Resistant Boot (Little/Big Kid) A popular short boot for youth, featuring a soft suede upper and a cozy wool blend lining/footbed for warmth. It's treated with NeverWet technology for water-resistance and has a durable, lightweight rubber outsole." },
                new Products { ProductID = 33, Name = "Crocs Kids' Classic Fuzz Lined Clog Little Kid", Price = 56M, ImageUrl = "~/Assets/images/Kids/shoes_kid7.png", Category = "Lifestyles/Casual", ProductUrl = "#", Gender="Kids", Sale = 0, ImageBack = "~/Assets/images/Kids/anh7_back.png", ImageLeft = "~/Assets/images/Kids/anh7_left.png", ImageTop = "~/Assets/images/Kids/anh7_top.png", ImageUnder = "~/Assets/images/Kids/anh7_under.png", Description="Crocs Kids' Classic Fuzz Lined Clog (Little Kid) The classic, lightweight Crocs clog adapted for cooler weather. It features a soft, permanently attached fuzzy lining inside the Croslite foam construction, providing comfortable cushioning and warmth for both indoor and outdoor wear." },
                new Products { ProductID = 34, Name = "Skechers Kids' Elite Sport Tread Slip On Sneaker Little/Big Kid", Price = 47M, ImageUrl = "~/Assets/images/Kids/shoes_kid8.png", Category = "Sports", ProductUrl = "#", Gender="Kids", Sale = 0, ImageBack = "~/Assets/images/Kids/anh8_back.png", ImageLeft = "~/Assets/images/Kids/anh8_left.png", ImageTop = "~/Assets/images/Kids/anh8_top.png", ImageUnder = "~/Assets/images/Kids/anh8_under.png", Description="Skechers Kids' Elite Sport Tread Slip On Sneaker (Little/Big Kid) A comfortable and durable slip-on athletic sneaker for children. It typically features a stretch-laced front and a durable traction outsole, designed for active play and easy wear with Skechers' signature cushioned comfort." },
                new Products { ProductID = 35, Name = "Adidas Kids' Street Talk Sneaker Little Kid", Price = 1234M, ImageUrl = "~/Assets/images/Kids/shoes_kid9.png", Category = "Lifestyles/Casual", ProductUrl = "#", Gender="Kids", Sale = 10, ImageBack = "~/Assets/images/Kids/anh9_back.png", ImageLeft = "~/Assets/images/Kids/anh9_left.png", ImageTop = "~/Assets/images/Kids/anh9_top.png", ImageUnder = "~/Assets/images/Kids/anh9_under.png", Description="Adidas Kids' Street Talk Sneaker (Little Kid) A street-ready sneaker for kids that blends classic athletic style with added support. It often features a durable synthetic upper with the signature 3-Stripes, a protective rubber shell toe, and a lace-up front reinforced with a hook-and-loop strap." },
            };
            Application["AllProducts"] = allProducts;
            Application["MenProductList"] = allProducts.Where(p => p.Gender == "Men").ToList();
            Application["WomenProductList"] = allProducts.Where(p => p.Gender == "Women").ToList();
            Application["KidsProductList"] = allProducts.Where(p => p.Gender == "Kids").ToList();
            foreach(var p in allProducts)
            {
                p.ProductUrl = $"~/Product_Detail.aspx?type={p.Gender.ToLower()}&id={p.ProductID}";
            }
            Application["dstk"] = new List<User>();
            User tk = new User();
            tk.Username = "admin";
            tk.Password = "12345678";
            tk.Surname = "Ad";
            tk.Name = "Admin";
            tk.Email = "admin@gmail.com";
            tk.Phone = "0123456789";
            tk.QueQuan ="Hà Nội";
            List<User> ds = (List<User>)Application["dstk"];
            ds.Add(tk);
            Application["dstk"] = ds;

            Application["AllReviews"] = new List<Review>
{
    new Review { ReviewId = 1, ProductID = 2, Author = "admin", Rating = 5, Content = "Excellent!", DatePosted = "10/10/2025 09:00" },
    new Review { ReviewId = 2, ProductID = 2, Author = "duy", Rating = 4, Content = "Nice shoes but delivery slow.", DatePosted = "12/10/2025 14:00" }
};
            Application["NextReviewId"] = 3;

            Application["OrderHistory"] = new List<Order>();

        }

        protected void Session_Start(object sender, EventArgs e)
        {

        }

        protected void Application_BeginRequest(object sender, EventArgs e)
        {

        }

        protected void Application_AuthenticateRequest(object sender, EventArgs e)
        {

        }

        protected void Application_Error(object sender, EventArgs e)
        {

        }

        protected void Session_End(object sender, EventArgs e)
        {

        }

        protected void Application_End(object sender, EventArgs e)
        {

        }
    }
}